package ComponentePresentacion;

import ComponenteClase.Categoria;
import ComponenteNegocio.NegocioCategoria;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
/**
 * @author Richard
 * @version 1.0
 * 
 * @author Mamani Bedregal
 * @version 2.0
 *
 * 
 * @author Rodriguez Zelada
 * @version 2.1
 */

public abstract class FormularioListaCategorias extends javax.swing.JDialog {
    private DefaultTableModel tablaCategoria= new DefaultTableModel();
    private FormularioCategoria formularioCategoria;
    private TableRowSorter rowSorter;

 /**
    * Método que muestra en el formulario un listado de transacciones realizadas.
    * @param formularioTransaccion lista las categorias de producto segun los campos en la base de datos
    */     
    public FormularioListaCategorias(final FormularioCategoria formularioCategoria, boolean modal) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            e.printStackTrace();
        }
        initComponents();
        String listaTituloTabla[]={"COD.CATEG","NOMBRE","DETALLE","DIRECCION URL(IMAGEN)"};
        tablaCategoria.setColumnIdentifiers(listaTituloTabla);
        try{
            NegocioCategoria categoriaNegocio = new NegocioCategoria();
        for(Categoria categoria : categoriaNegocio.mostrarCategoria()){
            String datoTabla[]={String.valueOf(categoria.getCodigoCategoria()),categoria.getNombreCategoria(),categoria.getDetalleCategoria(),categoria.getImagenCategoria()};
            tablaCategoria.addRow(datoTabla);
        }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "ERROR: "+e.getMessage());
        }       
        jCategoria.setModel(tablaCategoria);
        this.formularioCategoria = formularioCategoria;
        jCategoria.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                final int fila = jCategoria.rowAtPoint(e.getPoint());
                final int columna = jCategoria.columnAtPoint(e.getPoint());
                if ((fila > -1) && (columna > -1)) {
                    try {
                        NegocioCategoria categoriaNegocio =  new NegocioCategoria();
                        Categoria categoria = categoriaNegocio.buscarCategoriaCodigo(Integer.parseInt(String.valueOf(tablaCategoria.getValueAt(fila, 0))));
                        formularioCategoria.txtnombreCat.setEnabled(true);
                        formularioCategoria.txtdetalleCat.setEnabled(true);
                        formularioCategoria.txtnombreCat.setText(categoria.getNombreCategoria());
                        formularioCategoria.txtdetalleCat.setText(categoria.getDetalleCategoria());
                        formularioCategoria.txtidCategoria.setText(String.valueOf(categoria.getCodigoCategoria()));
                        formularioCategoria.btnEditarCat.setEnabled(true);
                        formularioCategoria.btnEliminarCat.setEnabled(true);
                        formularioCategoria.btnCancelarCat.setEnabled(true);
                        formularioCategoria.btnAbrirCat.setEnabled(true);
                        formularioCategoria.btnNuevo.setEnabled(false);
                        formularioCategoria.JPImagenCat.removeAll();
                        try {
                            formularioCategoria.JPImagenCat.removeAll();
                            URL url = new URL(categoria.getImagenCategoria());
                            formularioCategoria.imagen.setObtenerUrlImagen(url);
                            formularioCategoria.imagen.mostrarImagen(formularioCategoria.JPImagenCat);
                        } catch (MalformedURLException ex) {
                            
                        }
                        
                    } catch (SQLException ex) {
                        Logger.getLogger(FormularioListaCategorias.class.getName()).log(Level.SEVERE, null, ex);
                        
                    }

                }
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jCategoria = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtbuscarCat = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CATEGORIAS DISPONIBLES");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(81, 105, 138));

        jCategoria.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jCategoria.setModel(tablaCategoria);
        jCategoria.setGridColor(new java.awt.Color(247, 254, 255));
        jScrollPane1.setViewportView(jCategoria);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LISTA DE CATEGORIAS");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Texto a buscar:");

        txtbuscarCat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbuscarCatKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(119, 119, 119))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtbuscarCat)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtbuscarCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtbuscarCatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbuscarCatKeyTyped
        txtbuscarCat.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + txtbuscarCat.getText()));
            }
            
        });
        
        rowSorter = new TableRowSorter(tablaCategoria);
        jCategoria.setRowSorter(rowSorter);
    }//GEN-LAST:event_txtbuscarCatKeyTyped

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormularioListaCategorias dialog = new FormularioListaCategorias(null, true) {};
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable jCategoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtbuscarCat;
    // End of variables declaration//GEN-END:variables

}
